import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from '@/components/ui/theme-provider'


//process
// import { ClerkProvider } from '@clerk/nextjs'
// import NextTopLoader from 'nextjs-toploader';


//
import Web3ModalProvider from '@/context/Web3Modal'






const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'Chat GPT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
        {/* <NextTopLoader /> */}


          <Web3ModalProvider>


            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
            
              {children}
              <Toaster />
            </ThemeProvider>

          </Web3ModalProvider>

        </body>
      </html>
    // </ClerkProvider>
  )
}
